# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('cricket', models.BooleanField(default=False)),
                ('badminton', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('volleyball', models.BooleanField(default=False)),
                ('chess', models.BooleanField(default=False)),
                ('carrom', models.BooleanField(default=False)),
                ('table_tennis', models.BooleanField(default=False)),
                ('tug_of_war', models.BooleanField(default=False)),
                ('athletics', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('s', 'Selected'), ('r', 'Rejected'), ('w', 'Waiting')], default='w', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyBadminton',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('badminton', models.BooleanField(default=False)),
                ('preferred_hand', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=6)),
                ('past', models.CharField(choices=[('District Level', 'District Level'), ('Zonals', 'Zonals'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('Never Played in Tournament', 'Never Played in Tournament')], default='Never Played in Tournament', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyCricket',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('player_type', models.CharField(choices=[('Opening-Batsman', 'Opening-Batsman'), ('Middle-Order-Batsman', 'Middle-Order-Batsman'), ('Wicket-Keeper-Batsman', 'Wicket-Keeper-Batsman'), ('All-rounder', 'All-rounder'), ('Spinner', 'Spinner'), ('Fast-Bowler', 'Fast-Bowler')], default='', max_length=30)),
                ('cricket', models.BooleanField(default=False)),
                ('preferred_hand', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
