# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_auto_20170804_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='applybadminton',
            name='fullname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
