# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0004_applybadminton_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyFootball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('football', models.BooleanField(default=False)),
                ('fullname', models.CharField(default='', max_length=30)),
                ('left_or_right', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=6)),
                ('position', models.CharField(choices=[('Forward', 'Forward'), ('Mid-fielder', 'Mid-fielder'), ('Defence', 'Defence')], default='Never Played in Tournament', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
