# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0005_applyfootball'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyBasketBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball', models.BooleanField(default=False)),
                ('fullname', models.CharField(default='', max_length=30)),
                ('past', models.CharField(choices=[('District Level', 'District Level'), ('Zonals', 'Zonals'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('Never Played in Tournament', 'Never Played in Tournament')], default='Never Played in Tournament', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
