# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_applycarrom_applytabletennis'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycricket',
            name='status',
            field=models.CharField(choices=[('s', 'Selected'), ('r', 'Rejected'), ('w', 'Waiting')], default='w', max_length=1),
        ),
    ]
