# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_applycricket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycricket',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
