# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trials', '0011_auto_20170818_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyAthletics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletics', models.BooleanField(default=False)),
                ('fullname', models.CharField(default='', max_length=30)),
                ('past', models.CharField(choices=[('District Level', 'District Level'), ('Zonals', 'Zonals'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('Never Played in Tournament', 'Never Played in Tournament')], default='Never Played in Tournament', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyTugOfWar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tug_of_war', models.BooleanField(default=False)),
                ('fullname', models.CharField(default='', max_length=30)),
                ('past', models.CharField(choices=[('District Level', 'District Level'), ('Zonals', 'Zonals'), ('State Level', 'State Level'), ('National Level', 'National Level'), ('Never Played in Tournament', 'Never Played in Tournament')], default='Never Played in Tournament', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applybadminton',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applybasketball',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applycarrom',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applychess',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyfootball',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applytabletennis',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applyvolleyball',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
