# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0012_auto_20170820_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCricketPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('fullname', models.CharField(default='', max_length=30)),
                ('player_type', models.CharField(choices=[('Opening-Batsman', 'Opening-Batsman'), ('Middle-Order-Batsman', 'Middle-Order-Batsman'), ('Wicket-Keeper-Batsman', 'Wicket-Keeper-Batsman'), ('All-rounder', 'All-rounder'), ('Spinner', 'Spinner'), ('Fast-Bowler', 'Fast-Bowler')], default='', max_length=30)),
                ('preferred_hand', models.CharField(choices=[('Right', 'Right'), ('Left', 'Left')], default='', max_length=6)),
            ],
        ),
    ]
