# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0013_selectedcricketplayers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCricketPlayers',
        ),
    ]
