# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
