# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecricket',
            name='closing_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedulecricket',
            name='starting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
