# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20170811_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecricket',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
