# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedulecricket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecricket',
            name='host',
            field=models.CommaSeparatedIntegerField(default=0, max_length=50),
        ),
    ]
