# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham17', '0004_auto_20170826_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecricket',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
