# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham17', '0005_schedulecricket_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTableCricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='', max_length=100)),
                ('matches_played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tie', models.IntegerField(default=0)),
            ],
        ),
    ]
