# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham17', '0007_auto_20170826_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstablecricket',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointstablecricket',
            name='team',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ME', 'ME'), ('CE + EI', 'CE + EI'), ('EN', 'EN'), ('MBA + MCA', 'MBA + MCA')], default='', max_length=100),
        ),
    ]
