# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saksham17', '0009_pointstablecricket_no_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecricket',
            name='type',
            field=models.CharField(default='League', max_length=20),
        ),
    ]
