# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saksham17', '0010_schedulecricket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='', max_length=20)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('overs_bowled', models.FloatField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('match_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saksham17.ScheduleCricket')),
            ],
        ),
    ]
